name: myshop
description: My Shop is Personal Online Shopping Mobile Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  responsive_sizer: ^3.0.5+1 #Responsive Layout Helper
  font_awesome_flutter: ^10.1.0  #Get Font Awesome Icons
  persistent_bottom_nav_bar_v2: ^4.1.10 #Animated Bottom NavBar
  carousel_slider: ^4.1.1 #Image Slider

  lottie: ^1.3.0 #Animation Provider (json)


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animation/

  fonts:
    - family: Gabriel
      fonts:
        - asset: assets/fonts/Gabriel-Sans-Bold.otf
          weight: 700
        - asset: assets/fonts/Gabriel-Sans-Normal.otf
        - asset: assets/fonts/Gabriel-Sans-Medium-Italic.otf
          style: italic


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
