name: myshop
description: My Shop is Personal Online Shopping Mobile Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  #UI
  responsive_sizer: ^3.0.8 #Responsive Layout Helper
  persistent_bottom_nav_bar_v2: ^4.1.11 #Animated Bottom NavBar
  carousel_slider: ^4.1.1 #Image Slider
  cached_network_image: ^3.2.1 #Store Network Image In Cache
  share_plus: ^4.0.4 #share button
  awesome_select: ^5.2.0 #Color-Size-Selector
  flutter_cart: ^0.0.7 #Add to cart Button
  pinch_zoom: ^1.0.0 #Zoom Image By Finger
  image_picker: ^0.8.5+3 #pic image from storage/Camera

  #Animation
  lottie: ^1.3.0 #Animation Provider (json)
  badges: ^2.0.2 #it will useful for showing number on notification icon
  slide_countdown: ^0.2.4 #count down slider implemented in Homepage
  flutter_advanced_drawer: ^1.3.2 #animated Sliding Drawer
  flutter_login: ^3.2.0 #flutter login-signup package

  #BackEnd
  http: ^0.13.4
  provider: ^6.0.2
  flutter_html: ^3.0.0-alpha.3
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.5.3+1
  timezone: ^0.8.0

  #Payment
  razorpay_flutter: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animation/
    - assets/images/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
